Add support for proxying dynamic authorization requests [RFC8559]
radsecproxy/radsecproxy pull request #77
Opened 2021-01-12 12:26 UTC by hjain-arista

Add support for proxying dynamic authorization (CoA and Disconnect) requests following [RFC8559](https://tools.ietf.org/html/rfc8559).

A quick rundown of the RFC -
RFC8559 specifies 2 additional radius attributes - Operator-Name and Operator-NAS-Identifier. Operator-Name contains the realm which is used by intermediate proxies to determine where to forward the received CoA request. It works the same way as the User-Name attribute does for authentication and accounting requests, just in reverse. Proxies that receive CoA requests look up the realm in the Operator-Name attribute in a logical "realm routing table" and then the packet is sent to the next-hop server configured for that realm. If the proxy cannot find a destination for the request or if no Operator-Name attribute exists in the request, the proxy will return a NAK with Error-Cause 502 ("Request Not Routable").
Operator-NAS-Identifier is used by the end CoA server and the proxy must pass it unchanged.

Following changes are introduced -

- Add an attribute **dynAuthServer** to the realm config block. This attribute specifies the next-hop server to forward the CoA request to corresponding to a realm.
- Add an attribute **useDynAuthPort** of type Boolean to the server config block. If this is set to ON and no port is specified for the server, then default CoA port is used. This is 3799 for UDP/TCP and 2083 for TLS/DTLS.
- Update radsrv function to handle CoA/Disconnect requests as well. If _Operator-Name_ attribute is not present or if value of _Operator-Name_ attribute is not valid (the first character is not an ascii "1") or if the realm is unknown by the proxy, then a NAK packet containing Error-Cause attribute value =  502 ("Request not Routable") is sent back.
- Add an attribute **DynAuthResponse** of type Boolean to the realm config block. If this is set to ON and no **dynAuthServer** is configured for the realm, then a NAK will be sent for requests matching the realm. If this is set to OFF, then the request will be silently ignored.
- Any device which sends a CoA/Disconnect request must be configured as a client in the config file. Similarly, any device to which CoA requests are to be proxied to must be configured as a server in the config file.

2021-01-19 07:02 UTC, fmauchle requested changes
I guess the operator-name realm matching won't match anything that way. Note that the constructed regex expect a `@` in the string to be matched.

2021-01-20 09:27 UTC, hjain-arista commented on radsecproxy.c
> +        }
You're right. Thanks for pointing this out. Merged it with the block above.

2021-01-20 09:28 UTC, hjain-arista commented on radsecproxy.conf.5.in
> +
I understand. Removed this config and default dynAuthPort altogether.

2021-01-20 09:30 UTC, hjain-arista commented on radsecproxy.conf.5.in
> +.RE
Removed this config. Now the proxy will send a NAK if it receives a COA/Disconnect Request for a realm for which there is no `dynAuthServer` configured.

2021-01-20 09:40 UTC, hjain-arista commented
Since the constructed regex expect a `@` in the string to be matched, I made it so that after validating that first character of Operator-Name is indeed `1`, the proxy replaces the prefix `1` with `@`. So `1example.com` becomes `@example.com` and this string is used for regex matching with configured realms.
Another approach I could think of was to store a constructed regex string instead of a compiled regex in `realm->regex` and then change the regex itself in case of a COA Request but this will mean compiling regexes for each realm each time any request is processed, which I think is not desired.

2023-04-24 11:22 UTC, closed without merging